### ISSUE TITLE
const visibility keywords causing error (php 7.1)

### ISSUE THREAD

**Issue by cormacparle** [phpmd/phpmd#436]
The following php 7.1 code

    <?php

    class SomeClass
    {
        private const SOME_CONST = 1;
        private $someVariable;

        public function __construct($someVariable)
        {
                $this->someVariable = $someVariable;
        }
    }

gives me an error

    phpmd test.php text cleancode
    /var/data/www/users/xxx/test.php       -       Unexpected token: const, line: 5, col: 10, file: /var/data/www/users/xxx/test.php.

If I remove the `private` keyword befor the `const` then I get no error

    phpmd --version
    PHPMD 2.6.0

**Comment by ravage84** [comment]
This needs to be fixed in Pdepend. Can you open an issue there, please? May be check first, if it's already known.

**Comment by emirb** [comment]
Addressed in https://github.com/pdepend/pdepend/pull/349

**Comment by wirwolf** [comment]
Actual problem. I can not use phpmd in my project because this error emit exit with code 1

**Comment by emirb** [comment]
@wirwolf This has been fixed since 2.5.1. Can you please update?

**Comment by wirwolf** [comment]
@emirb 2.5.1 thanks. But i cannot understand how pdepend version affects this error.

**Comment by emirb** [comment]
phpmd is relying on pdepend for code analysis.

**Comment by padalec** [comment]
I have pdepend in version 
`PDepend 2.5.2`
 but this error still appear

**Comment by cormacparle** [comment]
Thanks for fixing this folks :)

**Comment by pszalko** [comment]
Is this fix already released?

**Comment by emirb** [comment]
cc @ravage84

**Comment by wirwolf** [comment]
> Is this fix already released?

i fixed this in https://github.com/SomeBlackMagic/phpmd

**Comment by fredericch** [comment]
Tried phpmd 2.7.0 (phar) with a php7.3 project. I still get `Unexpected token: const`
