### ISSUE TITLE
Compliance PHP 7.4

### ISSUE THREAD

**Issue by Plopix** [phpmd/phpmd#700]
Hello, I was wondering what was the plan about making PHPMD works for PHP 7.4

So far I have tried and obviously type properties are not working we got: 
```
-	Unexpected token:
```

but also destructuring does not make phpmd happy !

Thanks for maintaining!

**Comment by kylekatarnls** [comment]
Hello,

Destructuring arrays will be fixed with: https://github.com/pdepend/pdepend/pull/383 the PDepend parser needs to be upgraded for each feature and we're catching up a long maintenance pause.

**Comment by jeroenrnl** [comment]
This is also a PHP7.4 incompatibility:
eprecated: implode(): Passing glue string after array is deprecated. Swap the parameters in /var/lib/jenkins/workspace/XXX/vendor/phpmd/phpmd/src/main/php/PHPMD/RuleSetFactory.php on line 575
https://wiki.php.net/rfc/deprecations_php_7_4#implode_parameter_order_mix

**Comment by kylekatarnls** [comment]
Hi @jeroenrnl this is already fixed, please upgrade your version.

PHP 7.4 compliance is not about compatibility to run PHPMD (Last version of PHPMD can run on PHP 7.4 with no error or even deprecation as you can see in Travis-CI).

This issue is about the capacity of PDepend (static code analyzer of PHPMD) to understand all the new features of PHP 7.1 to 7.4, so the PRs above:
https://github.com/pdepend/pdepend/pull/415
https://github.com/pdepend/pdepend/pull/414
https://github.com/pdepend/pdepend/pull/413
https://github.com/pdepend/pdepend/pull/412
https://github.com/pdepend/pdepend/pull/411
https://github.com/pdepend/pdepend/pull/410
https://github.com/pdepend/pdepend/pull/408
https://github.com/pdepend/pdepend/pull/406
https://github.com/pdepend/pdepend/pull/405

PDepend 2.6.0 stable release should reach PHP 7.3 compliance and 2.7.0 will reach 7.4.

**Comment by kylekatarnls** [comment]
About the particular issue of typed properties, here is the PR that should fix it:
https://github.com/pdepend/pdepend/pull/414

**Comment by rafaelneris** [comment]
Same issue of typed properties.
pdepend dev-feature doesn't worked for me.
I'm getting following error:
Problem 1
    - phpmd/phpmd 2.8.1 requires pdepend/pdepend ^2.6 -> satisfiable by pdepend/pdepend[2.x-dev].
    - phpmd/phpmd 2.8.1 requires pdepend/pdepend ^2.6 -> satisfiable by pdepend/pdepend[2.x-dev].
    - phpmd/phpmd 2.8.1 requires pdepend/pdepend ^2.6 -> satisfiable by pdepend/pdepend[2.x-dev].
    - Can only install one of: pdepend/pdepend[2.x-dev, dev-feature/typed-properties].
    - Installation request for pdepend/pdepend dev-feature/typed-properties -> satisfiable by pdepend/pdepend[dev-feature/typed-properties].
    - Installation request for phpmd/phpmd 2.8.1 -> satisfiable by phpmd/phpmd[2.8.1].
@kylekatarnls Can you help me?

**Comment by chrBrd** [comment]
I've just pulled from `dev-master` in Composer, which I'm guessing now includes that PR.

Classnames and most primitives work, but I'm still getting `Unexpected token: array` in PHPMD.

**Comment by kylekatarnls** [comment]
Hello we need the complete stack trace and the code you run PHPMD on. Thanks.

**Comment by chrBrd** [comment]
I discovered the issue defining `array` class properties in a Symfony project, but I can repeat the behaviour with just this:

```php
// PHPMD outputs 'Unexpected token: array, line: 5, col: 12, file: Foo.php'

<?php

class Foo
{
    public array $bar = [1, 2, 3];
}
```

As for the stack trace, what exactly are you after? PHPMD doesn't throw an exception, it runs normally and exits; there's no PHP stack trace to provide you with.

**Comment by chrBrd** [comment]
In order to replicate the issue with PDepend's test suite:

1. Add `public array $list;` to the `User` class in `testTypedProperties.php`
2. Run PHPUnit on `PDepend\Source\Language\PHP\PHPParserVersion74Test::testTypedProperties()`

Result:
```
PDepend\Source\Parser\UnexpectedTokenException : Unexpected token: array, line: 8, col: 12, file: /opt/project/pdepend/src/test/resources/files/Source/Language/PHP/PHPParserVersion74/testTypedProperties.php.
 /opt/project/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php:7133
 /opt/project/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php:1015
 /opt/project/pdepend/src/main/php/PDepend/Source/Language/PHP/PHPParserVersion71.php:158
 /opt/project/pdepend/src/main/php/PDepend/Source/Language/PHP/PHPParserVersion74.php:70
 /opt/project/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php:995
 /opt/project/pdepend/src/main/php/PDepend/Source/Language/PHP/PHPParserVersion74.php:75
 /opt/project/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php:881
 /opt/project/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php:718
 /opt/project/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php:5896
 /opt/project/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php:393
 /opt/project/pdepend/src/test/php/PDepend/AbstractTest.php:905
 /opt/project/pdepend/src/test/php/PDepend/AbstractTest.php:829
 /opt/project/pdepend/src/test/php/PDepend/AbstractTest.php:294
 /opt/project/pdepend/src/test/php/PDepend/Source/Language/PHP/PHPParserVersion74Test.php:72
```

**Comment by kylekatarnls** [comment]
Thanks a lot. This is all we need to fix it.

**Comment by chrBrd** [comment]
No bother at all - thank *you* for this tool.

**Comment by cl1ck** [comment]
Same problem with nullable typed properties:
1. Add `public ?object $object;`  to the User class in testTypedProperties.php
2. Run PHPUnit on PDepend\Source\Language\PHP\PHPParserVersion74Test::testTypedProperties()

Result:
```
PDepend\Source\Parser\UnexpectedTokenException: Unexpected token: ?, line: 6, col: 12, file: /pdepend/src/test/resources/files/Source/Language/PHP/PHPParserVersion74/testTypedProperties.php.

/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php:7133
/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php:1015
/pdepend/src/main/php/PDepend/Source/Language/PHP/PHPParserVersion71.php:158
/pdepend/src/main/php/PDepend/Source/Language/PHP/PHPParserVersion74.php:70
/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php:995
/pdepend/src/main/php/PDepend/Source/Language/PHP/PHPParserVersion74.php:75
/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php:881
/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php:718
/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php:5896
/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php:393
/pdepend/src/test/php/PDepend/AbstractTest.php:905
/pdepend/src/test/php/PDepend/AbstractTest.php:829
/pdepend/src/test/php/PDepend/AbstractTest.php:294
/pdepend/src/test/php/PDepend/Source/Language/PHP/PHPParserVersion74Test.php:72
```

**Comment by realshadow** [comment]
Same problem with nullable typed properties:

- Add `public \Closure $closure;` to the User class in testTypedProperties.php
- Run PHPUnit on PDepend\Source\Language\PHP\PHPParserVersion74Test::testTypedProperties()

```
PDepend\Source\Language\PHP\PHPParserVersion74Test::testTypedProperties
PDepend\Source\Parser\UnexpectedTokenException: Unexpected token: \, line: 7, col: 12, file: /var/www/phpmd/pdepend/src/test/resources/files/Source/Language/PHP/PHPParserVersion74/testTypedProperties.php.

/var/www/phpmd/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php:7133
/var/www/phpmd/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php:1015
/var/www/phpmd/pdepend/src/main/php/PDepend/Source/Language/PHP/PHPParserVersion71.php:158
/var/www/phpmd/pdepend/src/main/php/PDepend/Source/Language/PHP/PHPParserVersion74.php:70
/var/www/phpmd/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php:995
/var/www/phpmd/pdepend/src/main/php/PDepend/Source/Language/PHP/PHPParserVersion74.php:75
/var/www/phpmd/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php:881
/var/www/phpmd/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php:718
/var/www/phpmd/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php:5896
/var/www/phpmd/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php:393
/var/www/phpmd/pdepend/src/test/php/PDepend/AbstractTest.php:905
/var/www/phpmd/pdepend/src/test/php/PDepend/AbstractTest.php:829
/var/www/phpmd/pdepend/src/test/php/PDepend/AbstractTest.php:294
/var/www/phpmd/pdepend/src/test/php/PDepend/Source/Language/PHP/PHPParserVersion74Test.php:72
```

(Shouldn't we post this in pdepend issues?)

**Comment by kylekatarnls** [comment]
I'm working on it and updated the test with:
```php
class User {
    public int $id;
    public float $money;
    public bool $active;
    public string $name;
    public array $list;
    public self $parent;
    public Role $role;
    public callable $event;
    public iterable $actions;
    public object $bag;
    public ?int $idN;
    public ?float $moneyN;
    public ?bool $activeN;
    public ?string $nameN;
    public ?array $listN;
    public ?self $parentN;
    public ?callable $eventN;
    public ?iterable $actionsN;
    public ?object $bagN;
    public ?Role $roleN;
    public $mixed;
}

```
So I'll make sure the next version will support nullable and any of those types hints.

**Comment by realshadow** [comment]
@kylekatarnls see my previous post before yours, `\Closure` or any class starting with `\` is missing
