### ISSUE TITLE
PHPMD fails to parse php files where trailing comma is used in multiline function or method arguments.

### ISSUE THREAD

**Issue by archfz** [phpmd/phpmd#889]
- PHPMD version: 2.10.0
- PHP Version: 8.0.5
- Installation type: composer
- Operating System / Distribution & Version: Ubuntu 20.04

### Current Behavior
When using trailing comma in multi-line function / method arguments, phpmd fails with following message:
```
ERROR while parsing 
--------------------
Unexpected token: ), line: 25, col: 5, file:
```
Example function:
```php
function myFunc(
  $a,
  $b,
) {}
```

### Expected Behavior
It should not fail as this is supported since php 7.4.

### Steps To Reproduce:
Explain **all** the steps you did to create this bug so we can reproduce it.

## Checks before submitting
* [x] Be sure that there isn't already an issue about this. See: [Issues list](https://github.com/phpmd/phpmd/issues)
* [x] Be sure that there isn't already a pull request about this. See: [Pull requests](https://github.com/phpmd/phpmd/pulls)
* [x] I have added every step to reproduce the bug.
* [x] If possible I added relevant code examples.
* [x] This issue is about 1 bug and nothing more.
* [x] The issue has a descriptive title. For example:  "JSON rendering failed on Windows for filenames with space".

**Comment by JBx0** [comment]
same here 
phpmd 2.10.1
pdepend 2.9.1 

still the same issue on empty constructor bodys

```
/phpmd(61): PHPMD\TextUI\Command::main(Array)
#24 {main}
        -       Unexpected token: ), line: 26, col: 5, file: foo.php
```
```
    public function __construct(
        private foo $foo,
        private bar $bar,
        private foobar $foobar,
    ) {
    }
```    	
Reproduction:
create a class with an empty constructor body  and run phpmd

**Comment by tvbeek** [comment]
@JBx0 thanks for your comment, as you can see this issue is still open. If you have the possibility you can create a PR with a fix, else we need to wait till someone else has the time to fix this. 😃

**Comment by JBx0** [comment]
@tvbeek xD yes I can see, but those are new versions I referenced ;)

**Comment by tvbeek** [comment]
@JBx0 as long as the issue is open it will not be changed in new versions :)

**Comment by JBx0** [comment]
@tvbeek I'd need some assistance for that since I have no clue of the codebase! 
But I'll check it out could u point me to the right classes? 
Trailing comma and false positive properties I'd take a look at.

**Comment by dshoreman** [comment]
@JBx0 This bug is more likely upstream rather than in PHPMD. See this stacktrace:

```
 Error: Unexpected token: ), line: 26, col: 5, file: ...
#0 ./vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(7322): PDepend\Source\Parser\UnexpectedTokenException->__construct()
#1 ./vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(7288): PDepend\Source\Language\PHP\AbstractPHPParser->getUnexpectedTokenException()
#2 ./vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(6757): PDepend\Source\Language\PHP\AbstractPHPParser->consumeToken()
#3 ./vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/PHPParserVersion70.php(505): PDepend\Source\Language\PHP\AbstractPHPParser->parseVariableDeclarator()
#4 ./vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(5674): PDepend\Source\Language\PHP\PHPParserVersion70->parseFormalParameter()
#5 ./vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/PHPParserVersion71.php(119): PDepend\Source\Language\PHP\AbstractPHPParser->parseFormalParameterOrTypeHintOrByReference()
#6 ./vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(5578): PDepend\Source\Language\PHP\PHPParserVersion71->parseFormalParameterOrTypeHintOrByReference()
#7 ./vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/PHPParserVersion80.php(180): PDepend\Source\Language\PHP\AbstractPHPParser->parseFormalParameterOrPrefix()
#8 ./vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(5611): PDepend\Source\Language\PHP\PHPParserVersion80->parseFormalParameterOrPrefix()
#9 ./vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(1273): PDepend\Source\Language\PHP\AbstractPHPParser->parseFormalParameters()
#10 ./vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(1231): PDepend\Source\Language\PHP\AbstractPHPParser->parseCallableDeclaration()
#11 ./vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(988): PDepend\Source\Language\PHP\AbstractPHPParser->parseMethodDeclaration()
#12 ./vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/PHPParserVersion74.php(87): PDepend\Source\Language\PHP\AbstractPHPParser->parseMethodOrFieldDeclaration()
#13 ./vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(887): PDepend\Source\Language\PHP\PHPParserVersion74->parseMethodOrFieldDeclaration()
#14 ./vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(723): PDepend\Source\Language\PHP\AbstractPHPParser->parseTypeBody()
#15 ./vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(6075): PDepend\Source\Language\PHP\AbstractPHPParser->parseClassDeclaration()
#16 ./vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(397): PDepend\Source\Language\PHP\AbstractPHPParser->parseOptionalStatement()
#17 ./vendor/pdepend/pdepend/src/main/php/PDepend/Engine.php(587): PDepend\Source\Language\PHP\AbstractPHPParser->parse()
#18 ./vendor/pdepend/pdepend/src/main/php/PDepend/Engine.php(335): PDepend\Engine->performParseProcess()
#19 ./vendor/phpmd/phpmd/src/main/php/PHPMD/Parser.php(95): PDepend\Engine->analyze()
#20 ./vendor/phpmd/phpmd/src/main/php/PHPMD/PHPMD.php(240): PHPMD\Parser->parse()
#21 ./vendor/phpmd/phpmd/src/main/php/PHPMD/TextUI/Command.php(136): PHPMD\PHPMD->processFiles()
#22 ./vendor/phpmd/phpmd/src/main/php/PHPMD/TextUI/Command.php(184): PHPMD\TextUI\Command->run()
#23 ./vendor/phpmd/phpmd/src/bin/phpmd(61): PHPMD\TextUI\Command::main()
#24 {main}
```

It might already be fixed by pdepend/pdepend#534. It was merged to master on May 13th, but it hasn't been tagged in a release yet. Short of depending on `2.x-dev`, there's not much we can do here beyond waiting

**Comment by JBx0** [comment]
> @JBx0 This bug is more likely upstream rather than in PHPMD. See this stacktrace:
> 
> ```
>  Error: Unexpected token: ), line: 26, col: 5, file: ...
> #0 ./vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(7322): PDepend\Source\Parser\UnexpectedTokenException->__construct()
> #1 ./vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(7288): PDepend\Source\Language\PHP\AbstractPHPParser->getUnexpectedTokenException()
> #2 ./vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(6757): PDepend\Source\Language\PHP\AbstractPHPParser->consumeToken()
> #3 ./vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/PHPParserVersion70.php(505): PDepend\Source\Language\PHP\AbstractPHPParser->parseVariableDeclarator()
> #4 ./vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(5674): PDepend\Source\Language\PHP\PHPParserVersion70->parseFormalParameter()
> #5 ./vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/PHPParserVersion71.php(119): PDepend\Source\Language\PHP\AbstractPHPParser->parseFormalParameterOrTypeHintOrByReference()
> #6 ./vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(5578): PDepend\Source\Language\PHP\PHPParserVersion71->parseFormalParameterOrTypeHintOrByReference()
> #7 ./vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/PHPParserVersion80.php(180): PDepend\Source\Language\PHP\AbstractPHPParser->parseFormalParameterOrPrefix()
> #8 ./vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(5611): PDepend\Source\Language\PHP\PHPParserVersion80->parseFormalParameterOrPrefix()
> #9 ./vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(1273): PDepend\Source\Language\PHP\AbstractPHPParser->parseFormalParameters()
> #10 ./vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(1231): PDepend\Source\Language\PHP\AbstractPHPParser->parseCallableDeclaration()
> #11 ./vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(988): PDepend\Source\Language\PHP\AbstractPHPParser->parseMethodDeclaration()
> #12 ./vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/PHPParserVersion74.php(87): PDepend\Source\Language\PHP\AbstractPHPParser->parseMethodOrFieldDeclaration()
> #13 ./vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(887): PDepend\Source\Language\PHP\PHPParserVersion74->parseMethodOrFieldDeclaration()
> #14 ./vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(723): PDepend\Source\Language\PHP\AbstractPHPParser->parseTypeBody()
> #15 ./vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(6075): PDepend\Source\Language\PHP\AbstractPHPParser->parseClassDeclaration()
> #16 ./vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(397): PDepend\Source\Language\PHP\AbstractPHPParser->parseOptionalStatement()
> #17 ./vendor/pdepend/pdepend/src/main/php/PDepend/Engine.php(587): PDepend\Source\Language\PHP\AbstractPHPParser->parse()
> #18 ./vendor/pdepend/pdepend/src/main/php/PDepend/Engine.php(335): PDepend\Engine->performParseProcess()
> #19 ./vendor/phpmd/phpmd/src/main/php/PHPMD/Parser.php(95): PDepend\Engine->analyze()
> #20 ./vendor/phpmd/phpmd/src/main/php/PHPMD/PHPMD.php(240): PHPMD\Parser->parse()
> #21 ./vendor/phpmd/phpmd/src/main/php/PHPMD/TextUI/Command.php(136): PHPMD\PHPMD->processFiles()
> #22 ./vendor/phpmd/phpmd/src/main/php/PHPMD/TextUI/Command.php(184): PHPMD\TextUI\Command->run()
> #23 ./vendor/phpmd/phpmd/src/bin/phpmd(61): PHPMD\TextUI\Command::main()
> #24 {main}
> ```
> 
> It might already be fixed by [pdepend/pdepend#534](https://github.com/pdepend/pdepend/pull/534). It was merged to master on May 13th, but it hasn't been tagged in a release yet. Short of depending on `2.x-dev`, there's not much we can do here beyond waiting.
> 
> For now though, `composer require --dev "pdepend/pdepend:2.x-dev"` is enough to "fix" it in your own project until next pdepend release.

pdepend dev branch is sadly not working, still the same issue.

**Comment by JBx0** [comment]
> @JBx0 This bug is more likely upstream rather than in PHPMD. See this stacktrace:
> 
> ```
>  Error: Unexpected token: ), line: 26, col: 5, file: ...
> #0 ./vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(7322): PDepend\Source\Parser\UnexpectedTokenException->__construct()
> #1 ./vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(7288): PDepend\Source\Language\PHP\AbstractPHPParser->getUnexpectedTokenException()
> #2 ./vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(6757): PDepend\Source\Language\PHP\AbstractPHPParser->consumeToken()
> #3 ./vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/PHPParserVersion70.php(505): PDepend\Source\Language\PHP\AbstractPHPParser->parseVariableDeclarator()
> #4 ./vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(5674): PDepend\Source\Language\PHP\PHPParserVersion70->parseFormalParameter()
> #5 ./vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/PHPParserVersion71.php(119): PDepend\Source\Language\PHP\AbstractPHPParser->parseFormalParameterOrTypeHintOrByReference()
> #6 ./vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(5578): PDepend\Source\Language\PHP\PHPParserVersion71->parseFormalParameterOrTypeHintOrByReference()
> #7 ./vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/PHPParserVersion80.php(180): PDepend\Source\Language\PHP\AbstractPHPParser->parseFormalParameterOrPrefix()
> #8 ./vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(5611): PDepend\Source\Language\PHP\PHPParserVersion80->parseFormalParameterOrPrefix()
> #9 ./vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(1273): PDepend\Source\Language\PHP\AbstractPHPParser->parseFormalParameters()
> #10 ./vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(1231): PDepend\Source\Language\PHP\AbstractPHPParser->parseCallableDeclaration()
> #11 ./vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(988): PDepend\Source\Language\PHP\AbstractPHPParser->parseMethodDeclaration()
> #12 ./vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/PHPParserVersion74.php(87): PDepend\Source\Language\PHP\AbstractPHPParser->parseMethodOrFieldDeclaration()
> #13 ./vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(887): PDepend\Source\Language\PHP\PHPParserVersion74->parseMethodOrFieldDeclaration()
> #14 ./vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(723): PDepend\Source\Language\PHP\AbstractPHPParser->parseTypeBody()
> #15 ./vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(6075): PDepend\Source\Language\PHP\AbstractPHPParser->parseClassDeclaration()
> #16 ./vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(397): PDepend\Source\Language\PHP\AbstractPHPParser->parseOptionalStatement()
> #17 ./vendor/pdepend/pdepend/src/main/php/PDepend/Engine.php(587): PDepend\Source\Language\PHP\AbstractPHPParser->parse()
> #18 ./vendor/pdepend/pdepend/src/main/php/PDepend/Engine.php(335): PDepend\Engine->performParseProcess()
> #19 ./vendor/phpmd/phpmd/src/main/php/PHPMD/Parser.php(95): PDepend\Engine->analyze()
> #20 ./vendor/phpmd/phpmd/src/main/php/PHPMD/PHPMD.php(240): PHPMD\Parser->parse()
> #21 ./vendor/phpmd/phpmd/src/main/php/PHPMD/TextUI/Command.php(136): PHPMD\PHPMD->processFiles()
> #22 ./vendor/phpmd/phpmd/src/main/php/PHPMD/TextUI/Command.php(184): PHPMD\TextUI\Command->run()
> #23 ./vendor/phpmd/phpmd/src/bin/phpmd(61): PHPMD\TextUI\Command::main()
> #24 {main}
> ```
> 
> It might already be fixed by [pdepend/pdepend#534](https://github.com/pdepend/pdepend/pull/534). It was merged to master on May 13th, but it hasn't been tagged in a release yet. Short of depending on `2.x-dev`, there's not much we can do here beyond waiting.
> 
> For now though, `composer require --dev "pdepend/pdepend:2.x-dev"` is enough to "fix" it in your own project until next pdepend release.

Works! Thx
composer require "pdepend/pdepend" "2.x-dev" --dev

**Comment by kylekatarnls** [comment]
You can update to last pdepend/pdepend now to get it fixed, phar version of 2.10.2 that will have it will be released this week too.
