### ISSUE TITLE
.pdepend folder grew to 45 GB

### ISSUE THREAD

**Issue by normadize** [phpmd/phpmd#90]
I posted the problem first in the PHPStorm tracker: http://youtrack.jetbrains.com/issue/WI-18654

I use PHPStorm as IDE which provides an interface to PMD.

Windows x64, php installed as standalone with all pear/pecl packages configured correctly as far as I can tell. PMD runs fine and also runs fine in PHPStorm. It just seems that it never cleans up after itself.

I was told to report this here as the PHPStorm devs won't fix it.

**Comment by DavidBadura** [comment]
+1 any news?

**Comment by normadize** [comment]
I see the dev finally paid attention 2h ago. Given how long it took for that to happen (no pun intended, we're all very busy people), a fix may take similarly long. 

A workaround would be a cron job that runs every M minutes and deletes all files that have not been accessed in H hours. On linux/macosx this will delete files not accessed in the last 24h:

    find /path/to/.pdepend -amin +1440 -exec rm {} \;

You may want to couple the above with the timestamp the .pdepend folder itself was last written to or else if you take a break from coding it will eventually delete all files in it. On linux/macosx you could replace 1440 above with `$(( ($(date +%s) - $(stat -f %Sm -t %s /path/to/.pdepend))/60 + 1440))` -- 24h after the last timestamp .pdepend was last written to.

NOTE: I haven't tested the above as I haven't used phpmd in a long while, but you get the gist.

**Comment by manuelpichler** [comment]
Just working on a simple GC for PDepend's cache

**Comment by ravage84** [comment]
@normadize the reason why I assigned this to me is because I am using Windows and PhpStorm, while @manuelpichler does not.

Also @manuelpichler already stated the following in the other ticket:
> This issue depends on PDepend and the next release still needs some work, so I move this ticket into milestone 2.3

We can keep this ticket open as it talks about the specific environment (Windows + PhpStorm) even though it should also be fixed once done in PDepend.

**Comment by qnxor** [comment]
@ravage84 no worries, I just replied to provide a possible workaround for those who still use phpmd.

**Comment by manuelpichler** [comment]
This issue should be fixed with commit [#56712b1](https://github.com/pdepend/pdepend/commit/56712b10c78a17f8305436c5a4ccdf3106107691). So I will make a bugfix release in PDepend and then update the dependency here.

**Comment by ihor-sviziev** [comment]
@manuelpichler good news!

**Comment by manuelpichler** [comment]
done, see release 2.2.1

**Comment by exi** [comment]
This is still happening for me at version 2.2.3.

We regularly run out of disk space on our build slaves with phpmd version 2.2.3.

Current .pdepend directory is 11GB in size.

**Comment by keksnicoh** [comment]
We encounter the same problem in 2.6.0 using php7.2 and ubuntu bionic as the file system (`.pdepend`) is not cleaned up after the job is done.

**Comment by npluis** [comment]
Same here on Ubuntu, folder is now 35G

I'm cleaning up with this command:
`find ~/.pdepend -type f -mtime +30 -exec rm \;`

But it would be nice if it could happen automatically

**Comment by vrkansagara** [comment]
I do use my own clean up script which has following command
`find $HOME/.pdepend -type f -mtime +3 -delete`
